### ISSUE TITLE
python-pyqt5 5.12-2 breaks webmacs

### ISSUE THREAD

**Issue by jagguli** [parkouss/webmacs#105]
```
Traceback (most recent call last):
  File "/home/steven/.local/bin/webmacs", line 11, in <module>
    load_entry_point('webmacs==0.8', 'console_scripts', 'webmacs')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/steven/.local/lib/python3.7/site-packages/webmacs-0.8-py3.7-linux-x86_64.egg/webmacs/main.py", line 27, in <module>
    from .ipc import IpcServer
  File "/home/steven/.local/lib/python3.7/site-packages/webmacs-0.8-py3.7-linux-x86_64.egg/webmacs/ipc.py", line 23, in <module>
    from . import version
  File "/home/steven/.local/lib/python3.7/site-packages/webmacs-0.8-py3.7-linux-x86_64.egg/webmacs/version.py", line 25, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineProfile
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
```

**Comment by jagguli** [comment]
after installing `python-pyqtwebengine` got this

```Traceback (most recent call last):
  File "/home/steven/.local/bin/webmacs", line 11, in <module>
    load_entry_point('webmacs==0.8', 'console_scripts', 'webmacs')()
  File "/home/steven/.local/lib/python3.7/site-packages/webmacs-0.8-py3.7-linux-x86_64.egg/webmacs/main.py", line 261, in main
    from .application import Application, _app_requires
  File "/home/steven/.local/lib/python3.7/site-packages/webmacs-0.8-py3.7-linux-x86_64.egg/webmacs/application.py", line 30, in <module>
    from .download_manager import DownloadManager
  File "/home/steven/.local/lib/python3.7/site-packages/webmacs-0.8-py3.7-linux-x86_64.egg/webmacs/download_manager/__init__.py", line 28, in <module>
    from .prompts import (DlChooseActionPrompt, DlOpenActionPrompt, DlPrompt,
  File "/home/steven/.local/lib/python3.7/site-packages/webmacs-0.8-py3.7-linux-x86_64.egg/webmacs/download_manager/prompts.py", line 18, in <module>
    from ..minibuffer.prompt import Prompt, FSModel, PromptTableModel, YesNoPrompt
  File "/home/steven/.local/lib/python3.7/site-packages/webmacs-0.8-py3.7-linux-x86_64.egg/webmacs/minibuffer/__init__.py", line 318, in <module>
    "Must be an instance of string"),
  File "/home/steven/.local/lib/python3.7/site-packages/webmacs-0.8-py3.7-linux-x86_64.egg/webmacs/variables.py", line 231, in define_variable
    var = Variable(name, doc, value, **kwargs)
  File "/home/steven/.local/lib/python3.7/site-packages/webmacs-0.8-py3.7-linux-x86_64.egg/webmacs/variables.py", line 25, in __init__
    assert isinstance(type, Type)
AssertionError
```

**Comment by TLATER** [comment]
I'm also using Arch (assuming that's what you use based on your package name) - a recent update did cause the first error (this is simply because a python library split in two, not related to webmacs).

As for the second, I can't reproduce it. Have you tried using the [`webmacs-git` AUR package](https://aur.archlinux.org/packages/webmacs-git/) to see if the issue persists with a setup that's known to work?

**Comment by jagguli** [comment]
hmm that actually worked, I was using webmacs from source.

not sure why that didn't work from source, maybe I didn't update from upstream.

Anyhoo many thanks, I'll mark this closed.

:heart: long live webmacs
