### ISSUE TITLE
error on installation

### ISSUE THREAD

**Issue by el3ctron** [parkouss/webmacs#14]
doing a sudo pip3 install .

Downloading/unpacking ruamel.yaml (from dateparser->webmacs==1.0)
  Downloading ruamel.yaml-0.15.35.tar.gz (260kB): 260kB downloaded
  Running setup.py (path:/tmp/pip_build_root/ruamel.yaml/setup.py) egg_info for package ruamel.yaml
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2273, in _dep_map
        return self.__dep_map
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2344, in __getattr__
        raise AttributeError(attr)
    AttributeError: _Distribution__dep_map
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/ruamel.yaml/setup.py", line 917, in <module>
        main()
      File "/tmp/pip_build_root/ruamel.yaml/setup.py", line 905, in main
        setup(**kw)
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 243, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python3.4/distutils/dist.py", line 280, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 276, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2100, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer)))
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2291, in requires
        dm = self._dep_map
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2281, in _dep_map
        if invalid_marker(marker):
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1186, in is_invalid_marker
        cls.evaluate_marker(text)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1284, in _markerlib_evaluate
        for key in env.keys():
    RuntimeError: dictionary changed size during iteration
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2273, in _dep_map

    return self.__dep_map

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2344, in __getattr__

    raise AttributeError(attr)

AttributeError: _Distribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/ruamel.yaml/setup.py", line 917, in <module>

    main()

  File "/tmp/pip_build_root/ruamel.yaml/setup.py", line 905, in main

    setup(**kw)

  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 243, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python3.4/distutils/dist.py", line 280, in __init__

    self.finalize_options()

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 276, in finalize_options

    ep.require(installer=self.fetch_build_egg)

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2100, in require

    working_set.resolve(self.dist.requires(self.extras),env,installer)))

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2291, in requires

    dm = self._dep_map

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2281, in _dep_map

    if invalid_marker(marker):

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1186, in is_invalid_marker

    cls.evaluate_marker(text)

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1284, in _markerlib_evaluate

    for key in env.keys():

RuntimeError: dictionary changed size during iteration

sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/ruamel.yaml
Storing debug log for failure in /home/el3ctron/.pip/pip.log

**Comment by parkouss** [comment]
It seems to be the error reported in https://bitbucket.org/ruamel/yaml/issues/95/pip3-install-ruamelyaml-fails. One comment mention that the command "pip3 install" has been issued using the pip installed by the os, which might be too old. I assume you are doing the same thing as you use sudo - please try to create a virtualenv instead and tell me if that works.

If that does work, it would be good to add a warning in the installation section of the webmacs readme file, or just remove the section using sudo.
