### ISSUE TITLE
print-buffer fails silently

### ISSUE THREAD

**Issue by ldutra** [parkouss/webmacs#143]
ERROR: Error calling command:
Traceback (most recent call last):
  File "/home/l/usr/src/webmacs/webmacs/keyboardhandler.py", line 247, in _handle_keypress
    self.call_handler.call(ctx, keymap, keypress,
  File "/home/l/usr/src/webmacs/webmacs/keyboardhandler.py", line 269, in call
    command(ctx)
  File "/home/l/usr/src/webmacs/webmacs/commands/__init__.py", line 41, in __call__
    return self.binding(ctx)
           ^^^^^^^^^^^^^^^^^
  File "/home/l/usr/src/webmacs/webmacs/commands/global.py", line 85, in commands
    COMMANDS[value](ctx)
  File "/home/l/usr/src/webmacs/webmacs/commands/__init__.py", line 41, in __call__
    return self.binding(ctx)
           ^^^^^^^^^^^^^^^^^
  File "/home/l/usr/src/webmacs/webmacs/commands/webbuffer.py", line 586, in print_buffer
    ok = dlg.exec() == dlg.Accepted
                       ^^^^^^^^^^^^
AttributeError: 'QPrintDialog' object has no attribute 'Accepted'

**Comment by ldutra** [comment]
More details:

When trying to print to a real printer, it just does not generate a print job.  The messages above are when trying to generate a PDF.
