### ISSUE TITLE
crash when switching split views

### ISSUE THREAD

**Issue by jagguli** [parkouss/webmacs#15]
ERROR: Error calling command:
Traceback (most recent call last):
  File "/home/steven/devel/webmacs/webmacs/keyboardhandler.py", line 192, in _handle_keypress
    self._call_command(result.command)
  File "/home/steven/devel/webmacs/webmacs/keyboardhandler.py", line 212, in _call_command
    command()
  File "/home/steven/devel/webmacs/webmacs/commands/__init__.py", line 63, in __call__
    self.binding()
  File "/home/steven/devel/webmacs/webmacs/commands/global.py", line 123, in split_window_bottom
    view = win.create_webview_on_bottom()
  File "/home/steven/devel/webmacs/webmacs/window.py", line 82, in create_webview_on_bottom
    view.container()
  File "/home/steven/devel/webmacs/webmacs/egrid.py", line 147, in insert_widget_bottom
    self.add_widget(widget, entry, entry.HORIZONTAL)
  File "/home/steven/devel/webmacs/webmacs/egrid.py", line 98, in add_widget
    parent_entry.do_split(item, direction)
  File "/home/steven/devel/webmacs/webmacs/egrid.py", line 31, in do_split
    assert self.item
AssertionError
Traceback (most recent call last):
  File "/home/steven/devel/webmacs/webmacs/keyboardhandler.py", line 58, in eventFilter
    set_local_keymap(obj.buffer().active_keymap())
AttributeError: 'QWebEnginePage' object has no attribute 'active_keymap'

**Comment by parkouss** [comment]
Do you have by any chance the list of steps to reproduce the issue?

**Comment by jagguli** [comment]
I think I did C-x 2, C-x 3, then C-x 1.

**Comment by jagguli** [comment]
Yep do that a couple of time and it crashes after some exceptions

```ERROR: Error calling command:
Traceback (most recent call last):
  File "/home/steven/.local/lib/python3.6/site-packages/webmacs/keyboardhandler.py", line 192, in _handle_keypress
    self._call_command(result.command)
  File "/home/steven/.local/lib/python3.6/site-packages/webmacs/keyboardhandler.py", line 212, in _call_command
    command()
  File "/home/steven/.local/lib/python3.6/site-packages/webmacs/commands/__init__.py", line 63, in __call__
    self.binding()
  File "/home/steven/.local/lib/python3.6/site-packages/webmacs/commands/global.py", line 112, in split_window_right
    view = win.create_webview_on_right()
  File "/home/steven/.local/lib/python3.6/site-packages/webmacs/window.py", line 74, in create_webview_on_right
    view.container()
  File "/home/steven/.local/lib/python3.6/site-packages/webmacs/egrid.py", line 138, in insert_widget_right
    self.add_widget(widget, entry, entry.VERTICAL)
  File "/home/steven/.local/lib/python3.6/site-packages/webmacs/egrid.py", line 98, in add_widget
    parent_entry.do_split(item, direction)
  File "/home/steven/.local/lib/python3.6/site-packages/webmacs/egrid.py", line 31, in do_split
    assert self.item
AssertionError

```

**Comment by parkouss** [comment]
Thanks! I spotted a couple of bugs and just pushed the fixes. I believe it fixes your issue, could you try it?

**Comment by jagguli** [comment]
looks good thanks :taco:
