### ISSUE TITLE
Starting webmacs fails.

### ISSUE THREAD

**Issue by stefanhusmann** [parkouss/webmacs#5]
Yesterday starting webmacs used to work. The webmacs script only contains "python -m webmacs.main" and python is python3. Now it fails, and I just updated krb5, auctex, ruby and erlang. 

[haawda@frege ~]$ webmacs&
[1] 8258
[haawda@frege ~]$ Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/webmacs/main.py", line 132, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/webmacs/main.py", line 110, in main
    app = Application(["webmacs"])
  File "/usr/lib/python3.6/site-packages/webmacs/application.py", line 75, in __init__
    self.profile.enable(self)
  File "/usr/lib/python3.6/site-packages/webmacs/profile.py", line 84, in enable
    assert f.open(QFile.ReadOnly | QFile.Text)
AssertionError

**Comment by parkouss** [comment]
The trace back shown above shows that it fails trying to open one of the file that normally is distributed with webmacs distribution.

Maybe there was an update of qt as well, or you accidentely removed some file in webmacs? could you check that your git clone is clean and try to reinstall webmacs?

**Comment by parkouss** [comment]
Oh, maybe I know what it is - if you are using the package you created for the aur, it may be currently unusable (some files missing, like non-python files and that would explain the error). I will fix that.

**Comment by stefanhusmann** [comment]
Thnaks for the update and the fix. It is working now.
